name: Create Pulumi Resource

on:
  repository_dispatch:
    types: [build]
    
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: payload
        run: echo ${{github.event.client_payload.repo}}
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Docker version
        run: docker --version
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.PRISMATIC_FACT_SECRETS }}'
      - name: Test & Login gcloud
        run: |
          gcloud projects list --sort-by=projectId --limit=5
          gcloud auth configure-docker gcr.io
      - name: install dependencies
        run: |
          npm install
          git clone https://github.com/${{github.event.client_payload.repo}}
          ls
      - name: Deploy
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_SECRETS }}
          pulumi login
          pulumi config set projectLocation pulumi-backend -s dev
          pulumi config set backend_port 80 -s dev
          sleep 1s
          pulumi up -s dev -y
          ls
          cat PulumiOutput_Public.txt
      - name: Create Deploy & Log file
        run: |
          echo 'This log a test' >> logs.txt
          echo 'This entrypoint test' >> entrypoint.txt
      - name: Push Deploy file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'entrypoint.txt'
          destination_repo: 'yabinboxes/pulumi-backend-MyCleanTechComp'
          destination_folder: 'entrypoint'
          user_email: 'yabin.monroy.1@gmail.com'
          user_name: 'yabinboxes'
          commit_message: 'first commit'
      - name: Push Log file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'logs.txt'
          destination_repo: 'yabinboxes/pulumi-backend-MyCleanTechComp'
          destination_folder: 'entrypoint'
          user_email: 'yabin.monroy.1@gmail.com'
          user_name: 'yabinboxes'
          commit_message: 'first commit'
      
