name: Create Pulumi Resource

on:
  repository_dispatch:
    types: [build]

# CLOUD_REPO_LOCATION
#

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # ---- functionality ----
      - name: payload
        run: echo ${{github.event.client_payload.cloudRepoLocation}}
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Docker version
        run: docker --version
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.PRISMATIC_FACT_SECRETS }}'
      - name: Test & Login gcloud
        run: |
          gcloud projects list --sort-by=projectId --limit=5
          gcloud auth configure-docker gcr.io
      - name: install dependencies
        run: |
          npm install
          git clone https://github.com/${{github.event.client_payload.cloudRepoLocation}}
          ls
      - name: Deploy
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_SECRETS }}
          pulumi login
          pulumi config set projectLocation ${{github.event.client_payload.cloudRepoLocation}} -s dev
          pulumi config set app_port ${{github.event.client_payload.appPort}} -s dev
          pulumi config set node_environment development -s dev
          sleep 1s
          pulumi up -s dev -y
      - name: Create Deploy & Log file
        run: |
          echo 'empty output logs' >> Logs.txt
          echo 'output url' >> PulumiOutput_Public.json
      - name: Push Deploy file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'PulumiOutput_Public.json'
          destination_repo: ${{github.event.client_payload.cloudRepoLocation}}
          destination_folder: 'cloud-files'
          user_email: ${{ github.event.client_payload.cloudEmailGithub }}
          user_name: ${{ github.event.client_payload.cloudUserGithub }}
          commit_message: 'first commit'
      - name: Push Log file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'Logs.txt'
          destination_repo: ${{github.event.client_payload.cloudRepoLocation}}
          destination_folder: 'cloud-files'
          user_email: ${{ github.event.client_payload.cloudEmailGithub }}
          user_name: ${{ github.event.client_payload.cloudUserGithub }}
          commit_message: 'first commit'
