name: Create Pulumi Resource

on: #[push]
  repository_dispatch:
    types: [build]
    
jobs:
  builds:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Docker version
        run: docker --version
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.PRISMATIC_FACT_SECRETS }}'
      - name: Test & Login gcloud
        run: |
          gcloud projects list --sort-by=projectId --limit=5
          gcloud auth configure-docker gcr.io
      - name: install dependencies
        run: |
          npm install
          git clone https://github.com/yabinboxes/pulumi-backend
          ls
      - name: Bucket name
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_SECRETS }}
          pulumi login
          pulumi config set projectLocation pulumi-backend -s dev
          pulumi config set backend_port 3000 -s dev
          sleep 1s
          pulumi up -s dev -y
      
